site_name: NixPHP
site_description: A modern, minimalist PHP microframework
theme:
  name: material
  logo: assets/nixphp-logo-small-square.png
  palette:
    - scheme: default
      primary: grey
      accent: light blue
  font:
    text: Lato
    code: Jetbrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - search.highlight
    - search.suggest
markdown_extensions:
  - pymdownx.highlight:
      linenums: false
      use_pygments: true
      pygments_style: friendly
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
#extra_css:
#  - assets/extra.css

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Routing: routing.md
  - Controllers: controllers.md
  - Response Handling: response_handling.md
  - Dependency Injection: dependency_injection.md
  - Events: events.md
  - Plugins: plugins.md
  - Error Handling: error_handling.md
  - File Downloads: file_downloads.md
  - Guard: guard.md
  - Using External Libraries: external_libraries.md
  - Best Practices: best_practices.md
  - Optional Plugins:
    - Views: views.md
    - Form Handling: form_handling.md
    - Database: database.md
    - Session: sessions.md


repo_url: https://github.com/nixphp/framework
repo_name: nixphp/framework
docs_dir: pages/
